document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
document.writeln("    <meta name=\"keywords\" content=\"\" />");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/bootstrap.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/head_style.css\" type=\"text/css\" media=\"all\" />");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/font-awesome.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/lightbox.css\">");
document.writeln("    <link href=\"http://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext\" rel=\"stylesheet\">");
document.writeln("    <link href=\"http://fonts.googleapis.com/css?family=Lobster&amp;subset=cyrillic,latin-ext,vietnamese\" rel=\"stylesheet\">");
document.writeln("    <link href=\"http://fonts.googleapis.com/css?family=Kanit:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,thai,vietnamese\" rel=\"stylesheet\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\"Main-agile\">");
document.writeln("    <div class=\"header\">");
document.writeln("        <div class=\"container\">");
document.writeln("            <div class=\"col-md-8 w3l_header_left\">");
document.writeln("               <ul>");
document.writeln("                    <li><span class=\"glyphicon glyphicon-earphone\" aria-hidden=\"true\"></span> +(61 3) 9035 5511</li>");
document.writeln("                    <li><span class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></span> <a href=\"mailto:info@example.com\">recycling_league@unimelb.edu.au</a></li>");
document.writeln("                    <li><span class=\"glyphicon glyphicon-map-marker add-w3\" aria-hidden=\"true\"></span>The University of Melbourne</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\"col-md-4 w3l_header_right\">");
document.writeln("                <div class=\"navbar-right social-icons\">");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\"#\" class=\"fa fa-facebook icon-border facebook\"> </a></li>");
document.writeln("                        <li><a href=\"#\" class=\"fa fa-twitter icon-border twitter\"> </a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\"clearfix\"> </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"header-bottom\">");
document.writeln("            <div class=\"container\">");
document.writeln("                <div class=\"col-md-3 logo-w3l\">");
document.writeln("                    <h1><a class=\"navbar-brand\" href=\"../views/home.html\"><span>R</span>ecycling Life</a></h1>");
document.writeln("                </div>");
document.writeln("                <div class=\"col-md-9 navi-w3l\">");
document.writeln("                    <nav class=\"navbar navbar-default\">");
document.writeln("                        <div class=\"container-fluid\">");
document.writeln("                            <div class=\"navbar-header\">");
document.writeln("                                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">");
document.writeln("                                    <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("                                    <span class=\"icon-bar\"></span>");
document.writeln("                                    <span class=\"icon-bar\"></span>");
document.writeln("                                    <span class=\"icon-bar\"></span>");
document.writeln("                                </button>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.writeln("                                <nav class=\"menu menu--francisco\">");
document.writeln("                                    <ul class=\"nav navbar-nav menu__list\">");
document.writeln("                                        <li class=\"menu__item menu__item--current\"><a href=\"../views/home.html\" class=\"menu__link\"><span class=\"menu__helper\">Home</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"#directory\" class=\"menu__link scroll\"><span class=\"menu__helper\">Recycling Directory</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"#grade\" class=\"menu__link scroll\"><span class=\"menu__helper\">My Grade</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"#account\" class=\"menu__link scroll\"><span class=\"menu__helper\">My Account</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"#login\" class=\"menu__link scroll\"><span class=\"menu__helper\">Log in</span></a></li>");
document.writeln("                                    </ul>");
document.writeln("                                </nav>");
document.writeln("                                <div class=\"clearfix\"></div>");
document.writeln("                            </div><!-- /.navbar-collapse -->");
document.writeln("                        </div>");
document.writeln("                    </nav>");
document.writeln("                </div>");
document.writeln("                <div class=\"clearfix\"></div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");